
baseURL = "http://example.org/"
languageCode = "pt-br"
title = "Meu Site Hugo"
theme = "PaperMod"

[params]
  env = "production"
  title = "Meu Site Hugo"
  description = "Descrição do site para SEO e redes sociais."
  keywords = ["Blog", "PaperMod", "Hugo"]
  author = "Seu Nome"
  images = ["/images/profile.jpg"]
  DateFormat = "02 de Janeiro de 2006"
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  assets.favicon = "/favicon.ico"
  assets.favicon16x16 = "/favicon-16x16.png"
  assets.favicon32x32 = "/favicon-32x32.png"
  assets.apple_touch_icon = "/apple-touch-icon.png"
  assets.safari_pinned_tab = "/safari-pinned-tab.svg"

  label.text = "Home"
  label.icon = "/apple-touch-icon.png"
  label.iconHeight = 35

  profileMode.enabled = true
  profileMode.title = "Seu Nome"
  profileMode.subtitle = "Sua descrição profissional"
  profileMode.imageUrl = "/images/profile.jpg"
  profileMode.imageWidth = 150
  profileMode.imageHeight = 150
  profileMode.imageTitle = "Foto de Perfil"
  profileMode.buttons = [
    { name = "Posts", url = "/posts/" },
    { name = "Sobre", url = "/about/" },
    { name = "Contato", url = "/contact/" }
  ]

  homeInfoParams.Title = "Olá 👋"
  homeInfoParams.Content = "Bem-vindo ao meu blog!"

  socialIcons = [
    { name = "github", url = "https://github.com/seu-usuario" },
    { name = "twitter", url = "https://twitter.com/seu-usuario" },
    { name = "linkedin", url = "https://linkedin.com/in/seu-usuario" }
  ]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "Sobre"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "contact"
    name = "Contato"
    url = "/contact/"
    weight = 30
